export const NUMBER_OF_ADMIN = 1;

export const NUMBER_OF_CUSTOMER = 500;

export const NUMBER_OF_ORDERS = 15000;

export const MIN_CARGO_QUANTITY = 1;
export const MAX_CARGO_QUANTITY = 5;

export const MAX_NUMBER_OF_EMPLOYEES_PER_TRANSACTION_POINT = 5;
export const MAX_NUMBER_OF_EMPLOYEES_PER_ASSEMBLY_POINT = 5;

export const MAX_TRANSACTION_POINT_PER_ASSEMBLY_POINT = 5;
export const MIN_TRANSACTION_POINT_PER_ASSEMBLY_POINT = 2;

export const MAX_DAYS_TO_RECEIVE = 100;
